name: minishell

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build executable
      run: |
        make

    - name: Run executable
      run: ./minishell
