name: cub3d

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build executable
      run: make

    - name: Run executable
      run: ./cub3D ./maps/chopin.cub
